### ISSUE TITLE
error 0x3e8e89 when updating a game

### ISSUE THREAD

**Issue by Pegoku** [HookedBehemoth/UpThemAll#2]

**Comment by HookedBehemoth** [comment]
This doesn't work if you nuked your prodinfo

**Comment by HookedBehemoth** [comment]
Actually the error is `CURLE_COULDNT_CONNECT` which could be anything that you do that prevents it from connecting to Nintendo's servers.
This homebrew doesn't enable piracy or anything. It just prompts your system to update all games.
